/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CreateTenantRouteImport } from './routes/create-tenant'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as MyCoursesRouteRouteImport } from './routes/my-courses/route'
import { Route as BackofficeRouteRouteImport } from './routes/backoffice/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as TenantSlugRouteRouteImport } from './routes/$tenantSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyCoursesIndexRouteImport } from './routes/my-courses/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice/index'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as MyCoursesCourseSlugRouteImport } from './routes/my-courses/$courseSlug'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as BackofficeWaitlistRouteImport } from './routes/backoffice/waitlist'
import { Route as BackofficeUsersRouteImport } from './routes/backoffice/users'
import { Route as BackofficeTenantsRouteImport } from './routes/backoffice/tenants'
import { Route as BackofficeFilesRouteImport } from './routes/backoffice/files'
import { Route as BackofficeEnrollmentsRouteImport } from './routes/backoffice/enrollments'
import { Route as BackofficeCertificatesRouteImport } from './routes/backoffice/certificates'
import { Route as _authVerifyEmailRouteImport } from './routes/__auth/verify-email'
import { Route as _authSignupRouteImport } from './routes/__auth/signup'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'
import { Route as TenantSlugConnectRouteImport } from './routes/$tenantSlug/connect'
import { Route as TenantSlugBillingRouteImport } from './routes/$tenantSlug/billing'
import { Route as ApiOgHomeRouteImport } from './routes/api/og/home'
import { Route as ApiOgCampusRouteImport } from './routes/api/og/campus'
import { Route as TenantSlugSiteCustomizationRouteImport } from './routes/$tenantSlug/site/customization'
import { Route as TenantSlugSiteConfigurationRouteImport } from './routes/$tenantSlug/site/configuration'
import { Route as TenantSlugSiteAiRouteImport } from './routes/$tenantSlug/site/ai'
import { Route as TenantSlugManagementUsersRouteImport } from './routes/$tenantSlug/management/users'
import { Route as TenantSlugManagementEnrollmentsRouteImport } from './routes/$tenantSlug/management/enrollments'
import { Route as TenantSlugContentVideosRouteImport } from './routes/$tenantSlug/content/videos'
import { Route as TenantSlugContentQuizzesRouteImport } from './routes/$tenantSlug/content/quizzes'
import { Route as TenantSlugContentModulesRouteImport } from './routes/$tenantSlug/content/modules'
import { Route as TenantSlugContentInstructorsRouteImport } from './routes/$tenantSlug/content/instructors'
import { Route as TenantSlugContentDocumentsRouteImport } from './routes/$tenantSlug/content/documents'
import { Route as TenantSlugContentCoursesRouteImport } from './routes/$tenantSlug/content/courses'
import { Route as TenantSlugContentCategoriesRouteImport } from './routes/$tenantSlug/content/categories'
import { Route as TenantSlugCheckoutSuccessRouteImport } from './routes/$tenantSlug/checkout/success'
import { Route as TenantSlugContentQuizzesIndexRouteImport } from './routes/$tenantSlug/content/quizzes.index'
import { Route as ApiOgCourseSlugRouteImport } from './routes/api/og/course.$slug'
import { Route as TenantSlugContentQuizzesQuizIdRouteImport } from './routes/$tenantSlug/content/quizzes.$quizId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTenantRoute = CreateTenantRouteImport.update({
  id: '/create-tenant',
  path: '/create-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRouteRoute = MyCoursesRouteRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRouteRoute = BackofficeRouteRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugRouteRoute = TenantSlugRouteRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesIndexRoute = MyCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyCoursesRouteRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesCourseSlugRoute = MyCoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => MyCoursesRouteRoute,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => CoursesRoute,
} as any)
const BackofficeWaitlistRoute = BackofficeWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeUsersRoute = BackofficeUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeTenantsRoute = BackofficeTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeFilesRoute = BackofficeFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeEnrollmentsRoute = BackofficeEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeCertificatesRoute = BackofficeCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const _authVerifyEmailRoute = _authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authSignupRoute = _authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const TenantSlugConnectRoute = TenantSlugConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugBillingRoute = TenantSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const ApiOgHomeRoute = ApiOgHomeRouteImport.update({
  id: '/api/og/home',
  path: '/api/og/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCampusRoute = ApiOgCampusRouteImport.update({
  id: '/api/og/campus',
  path: '/api/og/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugSiteCustomizationRoute =
  TenantSlugSiteCustomizationRouteImport.update({
    id: '/site/customization',
    path: '/site/customization',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugSiteConfigurationRoute =
  TenantSlugSiteConfigurationRouteImport.update({
    id: '/site/configuration',
    path: '/site/configuration',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugSiteAiRoute = TenantSlugSiteAiRouteImport.update({
  id: '/site/ai',
  path: '/site/ai',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugManagementUsersRoute =
  TenantSlugManagementUsersRouteImport.update({
    id: '/management/users',
    path: '/management/users',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugManagementEnrollmentsRoute =
  TenantSlugManagementEnrollmentsRouteImport.update({
    id: '/management/enrollments',
    path: '/management/enrollments',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentVideosRoute = TenantSlugContentVideosRouteImport.update({
  id: '/content/videos',
  path: '/content/videos',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugContentQuizzesRoute =
  TenantSlugContentQuizzesRouteImport.update({
    id: '/content/quizzes',
    path: '/content/quizzes',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentModulesRoute =
  TenantSlugContentModulesRouteImport.update({
    id: '/content/modules',
    path: '/content/modules',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentInstructorsRoute =
  TenantSlugContentInstructorsRouteImport.update({
    id: '/content/instructors',
    path: '/content/instructors',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentDocumentsRoute =
  TenantSlugContentDocumentsRouteImport.update({
    id: '/content/documents',
    path: '/content/documents',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentCoursesRoute =
  TenantSlugContentCoursesRouteImport.update({
    id: '/content/courses',
    path: '/content/courses',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentCategoriesRoute =
  TenantSlugContentCategoriesRouteImport.update({
    id: '/content/categories',
    path: '/content/categories',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugCheckoutSuccessRoute =
  TenantSlugCheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentQuizzesIndexRoute =
  TenantSlugContentQuizzesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantSlugContentQuizzesRoute,
  } as any)
const ApiOgCourseSlugRoute = ApiOgCourseSlugRouteImport.update({
  id: '/api/og/course/$slug',
  path: '/api/og/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugContentQuizzesQuizIdRoute =
  TenantSlugContentQuizzesQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => TenantSlugContentQuizzesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/backoffice': typeof BackofficeRouteRouteWithChildren
  '/my-courses': typeof MyCoursesRouteRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/create-tenant': typeof CreateTenantRoute
  '/profile': typeof ProfileRoute
  '/$tenantSlug/billing': typeof TenantSlugBillingRoute
  '/$tenantSlug/connect': typeof TenantSlugConnectRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signup': typeof _authSignupRoute
  '/verify-email': typeof _authVerifyEmailRoute
  '/backoffice/certificates': typeof BackofficeCertificatesRoute
  '/backoffice/enrollments': typeof BackofficeEnrollmentsRoute
  '/backoffice/files': typeof BackofficeFilesRoute
  '/backoffice/tenants': typeof BackofficeTenantsRoute
  '/backoffice/users': typeof BackofficeUsersRoute
  '/backoffice/waitlist': typeof BackofficeWaitlistRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/my-courses/$courseSlug': typeof MyCoursesCourseSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/my-courses/': typeof MyCoursesIndexRoute
  '/$tenantSlug/checkout/success': typeof TenantSlugCheckoutSuccessRoute
  '/$tenantSlug/content/categories': typeof TenantSlugContentCategoriesRoute
  '/$tenantSlug/content/courses': typeof TenantSlugContentCoursesRoute
  '/$tenantSlug/content/documents': typeof TenantSlugContentDocumentsRoute
  '/$tenantSlug/content/instructors': typeof TenantSlugContentInstructorsRoute
  '/$tenantSlug/content/modules': typeof TenantSlugContentModulesRoute
  '/$tenantSlug/content/quizzes': typeof TenantSlugContentQuizzesRouteWithChildren
  '/$tenantSlug/content/videos': typeof TenantSlugContentVideosRoute
  '/$tenantSlug/management/enrollments': typeof TenantSlugManagementEnrollmentsRoute
  '/$tenantSlug/management/users': typeof TenantSlugManagementUsersRoute
  '/$tenantSlug/site/ai': typeof TenantSlugSiteAiRoute
  '/$tenantSlug/site/configuration': typeof TenantSlugSiteConfigurationRoute
  '/$tenantSlug/site/customization': typeof TenantSlugSiteCustomizationRoute
  '/api/og/campus': typeof ApiOgCampusRoute
  '/api/og/home': typeof ApiOgHomeRoute
  '/$tenantSlug/content/quizzes/$quizId': typeof TenantSlugContentQuizzesQuizIdRoute
  '/api/og/course/$slug': typeof ApiOgCourseSlugRoute
  '/$tenantSlug/content/quizzes/': typeof TenantSlugContentQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-tenant': typeof CreateTenantRoute
  '/profile': typeof ProfileRoute
  '/$tenantSlug/billing': typeof TenantSlugBillingRoute
  '/$tenantSlug/connect': typeof TenantSlugConnectRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signup': typeof _authSignupRoute
  '/verify-email': typeof _authVerifyEmailRoute
  '/backoffice/certificates': typeof BackofficeCertificatesRoute
  '/backoffice/enrollments': typeof BackofficeEnrollmentsRoute
  '/backoffice/files': typeof BackofficeFilesRoute
  '/backoffice/tenants': typeof BackofficeTenantsRoute
  '/backoffice/users': typeof BackofficeUsersRoute
  '/backoffice/waitlist': typeof BackofficeWaitlistRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/my-courses/$courseSlug': typeof MyCoursesCourseSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/my-courses': typeof MyCoursesIndexRoute
  '/$tenantSlug/checkout/success': typeof TenantSlugCheckoutSuccessRoute
  '/$tenantSlug/content/categories': typeof TenantSlugContentCategoriesRoute
  '/$tenantSlug/content/courses': typeof TenantSlugContentCoursesRoute
  '/$tenantSlug/content/documents': typeof TenantSlugContentDocumentsRoute
  '/$tenantSlug/content/instructors': typeof TenantSlugContentInstructorsRoute
  '/$tenantSlug/content/modules': typeof TenantSlugContentModulesRoute
  '/$tenantSlug/content/videos': typeof TenantSlugContentVideosRoute
  '/$tenantSlug/management/enrollments': typeof TenantSlugManagementEnrollmentsRoute
  '/$tenantSlug/management/users': typeof TenantSlugManagementUsersRoute
  '/$tenantSlug/site/ai': typeof TenantSlugSiteAiRoute
  '/$tenantSlug/site/configuration': typeof TenantSlugSiteConfigurationRoute
  '/$tenantSlug/site/customization': typeof TenantSlugSiteCustomizationRoute
  '/api/og/campus': typeof ApiOgCampusRoute
  '/api/og/home': typeof ApiOgHomeRoute
  '/$tenantSlug/content/quizzes/$quizId': typeof TenantSlugContentQuizzesQuizIdRoute
  '/api/og/course/$slug': typeof ApiOgCourseSlugRoute
  '/$tenantSlug/content/quizzes': typeof TenantSlugContentQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/__auth': typeof _authRouteRouteWithChildren
  '/backoffice': typeof BackofficeRouteRouteWithChildren
  '/my-courses': typeof MyCoursesRouteRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/create-tenant': typeof CreateTenantRoute
  '/profile': typeof ProfileRoute
  '/$tenantSlug/billing': typeof TenantSlugBillingRoute
  '/$tenantSlug/connect': typeof TenantSlugConnectRoute
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/login': typeof _authLoginRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__auth/signup': typeof _authSignupRoute
  '/__auth/verify-email': typeof _authVerifyEmailRoute
  '/backoffice/certificates': typeof BackofficeCertificatesRoute
  '/backoffice/enrollments': typeof BackofficeEnrollmentsRoute
  '/backoffice/files': typeof BackofficeFilesRoute
  '/backoffice/tenants': typeof BackofficeTenantsRoute
  '/backoffice/users': typeof BackofficeUsersRoute
  '/backoffice/waitlist': typeof BackofficeWaitlistRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/my-courses/$courseSlug': typeof MyCoursesCourseSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/my-courses/': typeof MyCoursesIndexRoute
  '/$tenantSlug/checkout/success': typeof TenantSlugCheckoutSuccessRoute
  '/$tenantSlug/content/categories': typeof TenantSlugContentCategoriesRoute
  '/$tenantSlug/content/courses': typeof TenantSlugContentCoursesRoute
  '/$tenantSlug/content/documents': typeof TenantSlugContentDocumentsRoute
  '/$tenantSlug/content/instructors': typeof TenantSlugContentInstructorsRoute
  '/$tenantSlug/content/modules': typeof TenantSlugContentModulesRoute
  '/$tenantSlug/content/quizzes': typeof TenantSlugContentQuizzesRouteWithChildren
  '/$tenantSlug/content/videos': typeof TenantSlugContentVideosRoute
  '/$tenantSlug/management/enrollments': typeof TenantSlugManagementEnrollmentsRoute
  '/$tenantSlug/management/users': typeof TenantSlugManagementUsersRoute
  '/$tenantSlug/site/ai': typeof TenantSlugSiteAiRoute
  '/$tenantSlug/site/configuration': typeof TenantSlugSiteConfigurationRoute
  '/$tenantSlug/site/customization': typeof TenantSlugSiteCustomizationRoute
  '/api/og/campus': typeof ApiOgCampusRoute
  '/api/og/home': typeof ApiOgHomeRoute
  '/$tenantSlug/content/quizzes/$quizId': typeof TenantSlugContentQuizzesQuizIdRoute
  '/api/og/course/$slug': typeof ApiOgCourseSlugRoute
  '/$tenantSlug/content/quizzes/': typeof TenantSlugContentQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantSlug'
    | '/backoffice'
    | '/my-courses'
    | '/courses'
    | '/create-tenant'
    | '/profile'
    | '/$tenantSlug/billing'
    | '/$tenantSlug/connect'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/backoffice/certificates'
    | '/backoffice/enrollments'
    | '/backoffice/files'
    | '/backoffice/tenants'
    | '/backoffice/users'
    | '/backoffice/waitlist'
    | '/courses/$courseSlug'
    | '/my-courses/$courseSlug'
    | '/sitemap/xml'
    | '/verify/$code'
    | '/$tenantSlug/'
    | '/backoffice/'
    | '/courses/'
    | '/my-courses/'
    | '/$tenantSlug/checkout/success'
    | '/$tenantSlug/content/categories'
    | '/$tenantSlug/content/courses'
    | '/$tenantSlug/content/documents'
    | '/$tenantSlug/content/instructors'
    | '/$tenantSlug/content/modules'
    | '/$tenantSlug/content/quizzes'
    | '/$tenantSlug/content/videos'
    | '/$tenantSlug/management/enrollments'
    | '/$tenantSlug/management/users'
    | '/$tenantSlug/site/ai'
    | '/$tenantSlug/site/configuration'
    | '/$tenantSlug/site/customization'
    | '/api/og/campus'
    | '/api/og/home'
    | '/$tenantSlug/content/quizzes/$quizId'
    | '/api/og/course/$slug'
    | '/$tenantSlug/content/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-tenant'
    | '/profile'
    | '/$tenantSlug/billing'
    | '/$tenantSlug/connect'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/backoffice/certificates'
    | '/backoffice/enrollments'
    | '/backoffice/files'
    | '/backoffice/tenants'
    | '/backoffice/users'
    | '/backoffice/waitlist'
    | '/courses/$courseSlug'
    | '/my-courses/$courseSlug'
    | '/sitemap/xml'
    | '/verify/$code'
    | '/$tenantSlug'
    | '/backoffice'
    | '/courses'
    | '/my-courses'
    | '/$tenantSlug/checkout/success'
    | '/$tenantSlug/content/categories'
    | '/$tenantSlug/content/courses'
    | '/$tenantSlug/content/documents'
    | '/$tenantSlug/content/instructors'
    | '/$tenantSlug/content/modules'
    | '/$tenantSlug/content/videos'
    | '/$tenantSlug/management/enrollments'
    | '/$tenantSlug/management/users'
    | '/$tenantSlug/site/ai'
    | '/$tenantSlug/site/configuration'
    | '/$tenantSlug/site/customization'
    | '/api/og/campus'
    | '/api/og/home'
    | '/$tenantSlug/content/quizzes/$quizId'
    | '/api/og/course/$slug'
    | '/$tenantSlug/content/quizzes'
  id:
    | '__root__'
    | '/'
    | '/$tenantSlug'
    | '/__auth'
    | '/backoffice'
    | '/my-courses'
    | '/courses'
    | '/create-tenant'
    | '/profile'
    | '/$tenantSlug/billing'
    | '/$tenantSlug/connect'
    | '/__auth/forgot-password'
    | '/__auth/login'
    | '/__auth/reset-password'
    | '/__auth/signup'
    | '/__auth/verify-email'
    | '/backoffice/certificates'
    | '/backoffice/enrollments'
    | '/backoffice/files'
    | '/backoffice/tenants'
    | '/backoffice/users'
    | '/backoffice/waitlist'
    | '/courses/$courseSlug'
    | '/my-courses/$courseSlug'
    | '/sitemap/xml'
    | '/verify/$code'
    | '/$tenantSlug/'
    | '/backoffice/'
    | '/courses/'
    | '/my-courses/'
    | '/$tenantSlug/checkout/success'
    | '/$tenantSlug/content/categories'
    | '/$tenantSlug/content/courses'
    | '/$tenantSlug/content/documents'
    | '/$tenantSlug/content/instructors'
    | '/$tenantSlug/content/modules'
    | '/$tenantSlug/content/quizzes'
    | '/$tenantSlug/content/videos'
    | '/$tenantSlug/management/enrollments'
    | '/$tenantSlug/management/users'
    | '/$tenantSlug/site/ai'
    | '/$tenantSlug/site/configuration'
    | '/$tenantSlug/site/customization'
    | '/api/og/campus'
    | '/api/og/home'
    | '/$tenantSlug/content/quizzes/$quizId'
    | '/api/og/course/$slug'
    | '/$tenantSlug/content/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantSlugRouteRoute: typeof TenantSlugRouteRouteWithChildren
  _authRouteRoute: typeof _authRouteRouteWithChildren
  BackofficeRouteRoute: typeof BackofficeRouteRouteWithChildren
  MyCoursesRouteRoute: typeof MyCoursesRouteRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  CreateTenantRoute: typeof CreateTenantRoute
  ProfileRoute: typeof ProfileRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiOgCampusRoute: typeof ApiOgCampusRoute
  ApiOgHomeRoute: typeof ApiOgHomeRoute
  ApiOgCourseSlugRoute: typeof ApiOgCourseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-tenant': {
      id: '/create-tenant'
      path: '/create-tenant'
      fullPath: '/create-tenant'
      preLoaderRoute: typeof CreateTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug': {
      id: '/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof TenantSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses/': {
      id: '/my-courses/'
      path: '/'
      fullPath: '/my-courses/'
      preLoaderRoute: typeof MyCoursesIndexRouteImport
      parentRoute: typeof MyCoursesRouteRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses/$courseSlug': {
      id: '/my-courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/my-courses/$courseSlug'
      preLoaderRoute: typeof MyCoursesCourseSlugRouteImport
      parentRoute: typeof MyCoursesRouteRoute
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/backoffice/waitlist': {
      id: '/backoffice/waitlist'
      path: '/waitlist'
      fullPath: '/backoffice/waitlist'
      preLoaderRoute: typeof BackofficeWaitlistRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/users': {
      id: '/backoffice/users'
      path: '/users'
      fullPath: '/backoffice/users'
      preLoaderRoute: typeof BackofficeUsersRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/tenants': {
      id: '/backoffice/tenants'
      path: '/tenants'
      fullPath: '/backoffice/tenants'
      preLoaderRoute: typeof BackofficeTenantsRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/files': {
      id: '/backoffice/files'
      path: '/files'
      fullPath: '/backoffice/files'
      preLoaderRoute: typeof BackofficeFilesRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/enrollments': {
      id: '/backoffice/enrollments'
      path: '/enrollments'
      fullPath: '/backoffice/enrollments'
      preLoaderRoute: typeof BackofficeEnrollmentsRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/certificates': {
      id: '/backoffice/certificates'
      path: '/certificates'
      fullPath: '/backoffice/certificates'
      preLoaderRoute: typeof BackofficeCertificatesRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/__auth/verify-email': {
      id: '/__auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof _authVerifyEmailRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/signup': {
      id: '/__auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof _authSignupRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/$tenantSlug/connect': {
      id: '/$tenantSlug/connect'
      path: '/connect'
      fullPath: '/$tenantSlug/connect'
      preLoaderRoute: typeof TenantSlugConnectRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/billing': {
      id: '/$tenantSlug/billing'
      path: '/billing'
      fullPath: '/$tenantSlug/billing'
      preLoaderRoute: typeof TenantSlugBillingRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/api/og/home': {
      id: '/api/og/home'
      path: '/api/og/home'
      fullPath: '/api/og/home'
      preLoaderRoute: typeof ApiOgHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/campus': {
      id: '/api/og/campus'
      path: '/api/og/campus'
      fullPath: '/api/og/campus'
      preLoaderRoute: typeof ApiOgCampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/site/customization': {
      id: '/$tenantSlug/site/customization'
      path: '/site/customization'
      fullPath: '/$tenantSlug/site/customization'
      preLoaderRoute: typeof TenantSlugSiteCustomizationRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/site/configuration': {
      id: '/$tenantSlug/site/configuration'
      path: '/site/configuration'
      fullPath: '/$tenantSlug/site/configuration'
      preLoaderRoute: typeof TenantSlugSiteConfigurationRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/site/ai': {
      id: '/$tenantSlug/site/ai'
      path: '/site/ai'
      fullPath: '/$tenantSlug/site/ai'
      preLoaderRoute: typeof TenantSlugSiteAiRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/management/users': {
      id: '/$tenantSlug/management/users'
      path: '/management/users'
      fullPath: '/$tenantSlug/management/users'
      preLoaderRoute: typeof TenantSlugManagementUsersRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/management/enrollments': {
      id: '/$tenantSlug/management/enrollments'
      path: '/management/enrollments'
      fullPath: '/$tenantSlug/management/enrollments'
      preLoaderRoute: typeof TenantSlugManagementEnrollmentsRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/videos': {
      id: '/$tenantSlug/content/videos'
      path: '/content/videos'
      fullPath: '/$tenantSlug/content/videos'
      preLoaderRoute: typeof TenantSlugContentVideosRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/quizzes': {
      id: '/$tenantSlug/content/quizzes'
      path: '/content/quizzes'
      fullPath: '/$tenantSlug/content/quizzes'
      preLoaderRoute: typeof TenantSlugContentQuizzesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/modules': {
      id: '/$tenantSlug/content/modules'
      path: '/content/modules'
      fullPath: '/$tenantSlug/content/modules'
      preLoaderRoute: typeof TenantSlugContentModulesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/instructors': {
      id: '/$tenantSlug/content/instructors'
      path: '/content/instructors'
      fullPath: '/$tenantSlug/content/instructors'
      preLoaderRoute: typeof TenantSlugContentInstructorsRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/documents': {
      id: '/$tenantSlug/content/documents'
      path: '/content/documents'
      fullPath: '/$tenantSlug/content/documents'
      preLoaderRoute: typeof TenantSlugContentDocumentsRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/courses': {
      id: '/$tenantSlug/content/courses'
      path: '/content/courses'
      fullPath: '/$tenantSlug/content/courses'
      preLoaderRoute: typeof TenantSlugContentCoursesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/categories': {
      id: '/$tenantSlug/content/categories'
      path: '/content/categories'
      fullPath: '/$tenantSlug/content/categories'
      preLoaderRoute: typeof TenantSlugContentCategoriesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/checkout/success': {
      id: '/$tenantSlug/checkout/success'
      path: '/checkout/success'
      fullPath: '/$tenantSlug/checkout/success'
      preLoaderRoute: typeof TenantSlugCheckoutSuccessRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/quizzes/': {
      id: '/$tenantSlug/content/quizzes/'
      path: '/'
      fullPath: '/$tenantSlug/content/quizzes/'
      preLoaderRoute: typeof TenantSlugContentQuizzesIndexRouteImport
      parentRoute: typeof TenantSlugContentQuizzesRoute
    }
    '/api/og/course/$slug': {
      id: '/api/og/course/$slug'
      path: '/api/og/course/$slug'
      fullPath: '/api/og/course/$slug'
      preLoaderRoute: typeof ApiOgCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/content/quizzes/$quizId': {
      id: '/$tenantSlug/content/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/$tenantSlug/content/quizzes/$quizId'
      preLoaderRoute: typeof TenantSlugContentQuizzesQuizIdRouteImport
      parentRoute: typeof TenantSlugContentQuizzesRoute
    }
  }
}

interface TenantSlugContentQuizzesRouteChildren {
  TenantSlugContentQuizzesQuizIdRoute: typeof TenantSlugContentQuizzesQuizIdRoute
  TenantSlugContentQuizzesIndexRoute: typeof TenantSlugContentQuizzesIndexRoute
}

const TenantSlugContentQuizzesRouteChildren: TenantSlugContentQuizzesRouteChildren =
  {
    TenantSlugContentQuizzesQuizIdRoute: TenantSlugContentQuizzesQuizIdRoute,
    TenantSlugContentQuizzesIndexRoute: TenantSlugContentQuizzesIndexRoute,
  }

const TenantSlugContentQuizzesRouteWithChildren =
  TenantSlugContentQuizzesRoute._addFileChildren(
    TenantSlugContentQuizzesRouteChildren,
  )

interface TenantSlugRouteRouteChildren {
  TenantSlugBillingRoute: typeof TenantSlugBillingRoute
  TenantSlugConnectRoute: typeof TenantSlugConnectRoute
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
  TenantSlugCheckoutSuccessRoute: typeof TenantSlugCheckoutSuccessRoute
  TenantSlugContentCategoriesRoute: typeof TenantSlugContentCategoriesRoute
  TenantSlugContentCoursesRoute: typeof TenantSlugContentCoursesRoute
  TenantSlugContentDocumentsRoute: typeof TenantSlugContentDocumentsRoute
  TenantSlugContentInstructorsRoute: typeof TenantSlugContentInstructorsRoute
  TenantSlugContentModulesRoute: typeof TenantSlugContentModulesRoute
  TenantSlugContentQuizzesRoute: typeof TenantSlugContentQuizzesRouteWithChildren
  TenantSlugContentVideosRoute: typeof TenantSlugContentVideosRoute
  TenantSlugManagementEnrollmentsRoute: typeof TenantSlugManagementEnrollmentsRoute
  TenantSlugManagementUsersRoute: typeof TenantSlugManagementUsersRoute
  TenantSlugSiteAiRoute: typeof TenantSlugSiteAiRoute
  TenantSlugSiteConfigurationRoute: typeof TenantSlugSiteConfigurationRoute
  TenantSlugSiteCustomizationRoute: typeof TenantSlugSiteCustomizationRoute
}

const TenantSlugRouteRouteChildren: TenantSlugRouteRouteChildren = {
  TenantSlugBillingRoute: TenantSlugBillingRoute,
  TenantSlugConnectRoute: TenantSlugConnectRoute,
  TenantSlugIndexRoute: TenantSlugIndexRoute,
  TenantSlugCheckoutSuccessRoute: TenantSlugCheckoutSuccessRoute,
  TenantSlugContentCategoriesRoute: TenantSlugContentCategoriesRoute,
  TenantSlugContentCoursesRoute: TenantSlugContentCoursesRoute,
  TenantSlugContentDocumentsRoute: TenantSlugContentDocumentsRoute,
  TenantSlugContentInstructorsRoute: TenantSlugContentInstructorsRoute,
  TenantSlugContentModulesRoute: TenantSlugContentModulesRoute,
  TenantSlugContentQuizzesRoute: TenantSlugContentQuizzesRouteWithChildren,
  TenantSlugContentVideosRoute: TenantSlugContentVideosRoute,
  TenantSlugManagementEnrollmentsRoute: TenantSlugManagementEnrollmentsRoute,
  TenantSlugManagementUsersRoute: TenantSlugManagementUsersRoute,
  TenantSlugSiteAiRoute: TenantSlugSiteAiRoute,
  TenantSlugSiteConfigurationRoute: TenantSlugSiteConfigurationRoute,
  TenantSlugSiteCustomizationRoute: TenantSlugSiteCustomizationRoute,
}

const TenantSlugRouteRouteWithChildren = TenantSlugRouteRoute._addFileChildren(
  TenantSlugRouteRouteChildren,
)

interface _authRouteRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authLoginRoute: typeof _authLoginRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
  _authSignupRoute: typeof _authSignupRoute
  _authVerifyEmailRoute: typeof _authVerifyEmailRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authLoginRoute: _authLoginRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
  _authSignupRoute: _authSignupRoute,
  _authVerifyEmailRoute: _authVerifyEmailRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface BackofficeRouteRouteChildren {
  BackofficeCertificatesRoute: typeof BackofficeCertificatesRoute
  BackofficeEnrollmentsRoute: typeof BackofficeEnrollmentsRoute
  BackofficeFilesRoute: typeof BackofficeFilesRoute
  BackofficeTenantsRoute: typeof BackofficeTenantsRoute
  BackofficeUsersRoute: typeof BackofficeUsersRoute
  BackofficeWaitlistRoute: typeof BackofficeWaitlistRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteRouteChildren: BackofficeRouteRouteChildren = {
  BackofficeCertificatesRoute: BackofficeCertificatesRoute,
  BackofficeEnrollmentsRoute: BackofficeEnrollmentsRoute,
  BackofficeFilesRoute: BackofficeFilesRoute,
  BackofficeTenantsRoute: BackofficeTenantsRoute,
  BackofficeUsersRoute: BackofficeUsersRoute,
  BackofficeWaitlistRoute: BackofficeWaitlistRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteRouteWithChildren = BackofficeRouteRoute._addFileChildren(
  BackofficeRouteRouteChildren,
)

interface MyCoursesRouteRouteChildren {
  MyCoursesCourseSlugRoute: typeof MyCoursesCourseSlugRoute
  MyCoursesIndexRoute: typeof MyCoursesIndexRoute
}

const MyCoursesRouteRouteChildren: MyCoursesRouteRouteChildren = {
  MyCoursesCourseSlugRoute: MyCoursesCourseSlugRoute,
  MyCoursesIndexRoute: MyCoursesIndexRoute,
}

const MyCoursesRouteRouteWithChildren = MyCoursesRouteRoute._addFileChildren(
  MyCoursesRouteRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantSlugRouteRoute: TenantSlugRouteRouteWithChildren,
  _authRouteRoute: _authRouteRouteWithChildren,
  BackofficeRouteRoute: BackofficeRouteRouteWithChildren,
  MyCoursesRouteRoute: MyCoursesRouteRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  CreateTenantRoute: CreateTenantRoute,
  ProfileRoute: ProfileRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiOgCampusRoute: ApiOgCampusRoute,
  ApiOgHomeRoute: ApiOgHomeRoute,
  ApiOgCourseSlugRoute: ApiOgCourseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
