/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CreateTenantRouteImport } from './routes/create-tenant'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BackofficeRouteRouteImport } from './routes/backoffice/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as TenantSlugRouteRouteImport } from './routes/$tenantSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice/index'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug/index'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as BackofficeUsersRouteImport } from './routes/backoffice/users'
import { Route as BackofficeTenantsRouteImport } from './routes/backoffice/tenants'
import { Route as _authSignupRouteImport } from './routes/__auth/signup'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'
import { Route as TenantSlugSiteCustomizationRouteImport } from './routes/$tenantSlug/site/customization'
import { Route as TenantSlugSiteConfigurationRouteImport } from './routes/$tenantSlug/site/configuration'
import { Route as TenantSlugManagementUsersRouteImport } from './routes/$tenantSlug/management/users'
import { Route as TenantSlugContentVideosRouteImport } from './routes/$tenantSlug/content/videos'
import { Route as TenantSlugContentQuizzesRouteImport } from './routes/$tenantSlug/content/quizzes'
import { Route as TenantSlugContentModulesRouteImport } from './routes/$tenantSlug/content/modules'
import { Route as TenantSlugContentInstructorsRouteImport } from './routes/$tenantSlug/content/instructors'
import { Route as TenantSlugContentDocumentsRouteImport } from './routes/$tenantSlug/content/documents'
import { Route as TenantSlugContentCoursesRouteImport } from './routes/$tenantSlug/content/courses'
import { Route as TenantSlugContentCategoriesRouteImport } from './routes/$tenantSlug/content/categories'
import { Route as TenantSlugContentQuizzesQuizIdRouteImport } from './routes/$tenantSlug/content/quizzes.$quizId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTenantRoute = CreateTenantRouteImport.update({
  id: '/create-tenant',
  path: '/create-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRouteRoute = BackofficeRouteRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugRouteRoute = TenantSlugRouteRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => CoursesRoute,
} as any)
const BackofficeUsersRoute = BackofficeUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeTenantsRoute = BackofficeTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const _authSignupRoute = _authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const TenantSlugSiteCustomizationRoute =
  TenantSlugSiteCustomizationRouteImport.update({
    id: '/site/customization',
    path: '/site/customization',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugSiteConfigurationRoute =
  TenantSlugSiteConfigurationRouteImport.update({
    id: '/site/configuration',
    path: '/site/configuration',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugManagementUsersRoute =
  TenantSlugManagementUsersRouteImport.update({
    id: '/management/users',
    path: '/management/users',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentVideosRoute = TenantSlugContentVideosRouteImport.update({
  id: '/content/videos',
  path: '/content/videos',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugContentQuizzesRoute =
  TenantSlugContentQuizzesRouteImport.update({
    id: '/content/quizzes',
    path: '/content/quizzes',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentModulesRoute =
  TenantSlugContentModulesRouteImport.update({
    id: '/content/modules',
    path: '/content/modules',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentInstructorsRoute =
  TenantSlugContentInstructorsRouteImport.update({
    id: '/content/instructors',
    path: '/content/instructors',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentDocumentsRoute =
  TenantSlugContentDocumentsRouteImport.update({
    id: '/content/documents',
    path: '/content/documents',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentCoursesRoute =
  TenantSlugContentCoursesRouteImport.update({
    id: '/content/courses',
    path: '/content/courses',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentCategoriesRoute =
  TenantSlugContentCategoriesRouteImport.update({
    id: '/content/categories',
    path: '/content/categories',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugContentQuizzesQuizIdRoute =
  TenantSlugContentQuizzesQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => TenantSlugContentQuizzesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/backoffice': typeof BackofficeRouteRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/create-tenant': typeof CreateTenantRoute
  '/profile': typeof ProfileRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signup': typeof _authSignupRoute
  '/backoffice/tenants': typeof BackofficeTenantsRoute
  '/backoffice/users': typeof BackofficeUsersRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/$tenantSlug/content/categories': typeof TenantSlugContentCategoriesRoute
  '/$tenantSlug/content/courses': typeof TenantSlugContentCoursesRoute
  '/$tenantSlug/content/documents': typeof TenantSlugContentDocumentsRoute
  '/$tenantSlug/content/instructors': typeof TenantSlugContentInstructorsRoute
  '/$tenantSlug/content/modules': typeof TenantSlugContentModulesRoute
  '/$tenantSlug/content/quizzes': typeof TenantSlugContentQuizzesRouteWithChildren
  '/$tenantSlug/content/videos': typeof TenantSlugContentVideosRoute
  '/$tenantSlug/management/users': typeof TenantSlugManagementUsersRoute
  '/$tenantSlug/site/configuration': typeof TenantSlugSiteConfigurationRoute
  '/$tenantSlug/site/customization': typeof TenantSlugSiteCustomizationRoute
  '/$tenantSlug/content/quizzes/$quizId': typeof TenantSlugContentQuizzesQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-tenant': typeof CreateTenantRoute
  '/profile': typeof ProfileRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signup': typeof _authSignupRoute
  '/backoffice/tenants': typeof BackofficeTenantsRoute
  '/backoffice/users': typeof BackofficeUsersRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/$tenantSlug/content/categories': typeof TenantSlugContentCategoriesRoute
  '/$tenantSlug/content/courses': typeof TenantSlugContentCoursesRoute
  '/$tenantSlug/content/documents': typeof TenantSlugContentDocumentsRoute
  '/$tenantSlug/content/instructors': typeof TenantSlugContentInstructorsRoute
  '/$tenantSlug/content/modules': typeof TenantSlugContentModulesRoute
  '/$tenantSlug/content/quizzes': typeof TenantSlugContentQuizzesRouteWithChildren
  '/$tenantSlug/content/videos': typeof TenantSlugContentVideosRoute
  '/$tenantSlug/management/users': typeof TenantSlugManagementUsersRoute
  '/$tenantSlug/site/configuration': typeof TenantSlugSiteConfigurationRoute
  '/$tenantSlug/site/customization': typeof TenantSlugSiteCustomizationRoute
  '/$tenantSlug/content/quizzes/$quizId': typeof TenantSlugContentQuizzesQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/__auth': typeof _authRouteRouteWithChildren
  '/backoffice': typeof BackofficeRouteRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/create-tenant': typeof CreateTenantRoute
  '/profile': typeof ProfileRoute
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/login': typeof _authLoginRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__auth/signup': typeof _authSignupRoute
  '/backoffice/tenants': typeof BackofficeTenantsRoute
  '/backoffice/users': typeof BackofficeUsersRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/$tenantSlug/content/categories': typeof TenantSlugContentCategoriesRoute
  '/$tenantSlug/content/courses': typeof TenantSlugContentCoursesRoute
  '/$tenantSlug/content/documents': typeof TenantSlugContentDocumentsRoute
  '/$tenantSlug/content/instructors': typeof TenantSlugContentInstructorsRoute
  '/$tenantSlug/content/modules': typeof TenantSlugContentModulesRoute
  '/$tenantSlug/content/quizzes': typeof TenantSlugContentQuizzesRouteWithChildren
  '/$tenantSlug/content/videos': typeof TenantSlugContentVideosRoute
  '/$tenantSlug/management/users': typeof TenantSlugManagementUsersRoute
  '/$tenantSlug/site/configuration': typeof TenantSlugSiteConfigurationRoute
  '/$tenantSlug/site/customization': typeof TenantSlugSiteCustomizationRoute
  '/$tenantSlug/content/quizzes/$quizId': typeof TenantSlugContentQuizzesQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantSlug'
    | '/backoffice'
    | '/courses'
    | '/create-tenant'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/backoffice/tenants'
    | '/backoffice/users'
    | '/courses/$courseSlug'
    | '/$tenantSlug/'
    | '/backoffice/'
    | '/courses/'
    | '/$tenantSlug/content/categories'
    | '/$tenantSlug/content/courses'
    | '/$tenantSlug/content/documents'
    | '/$tenantSlug/content/instructors'
    | '/$tenantSlug/content/modules'
    | '/$tenantSlug/content/quizzes'
    | '/$tenantSlug/content/videos'
    | '/$tenantSlug/management/users'
    | '/$tenantSlug/site/configuration'
    | '/$tenantSlug/site/customization'
    | '/$tenantSlug/content/quizzes/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-tenant'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/backoffice/tenants'
    | '/backoffice/users'
    | '/courses/$courseSlug'
    | '/$tenantSlug'
    | '/backoffice'
    | '/courses'
    | '/$tenantSlug/content/categories'
    | '/$tenantSlug/content/courses'
    | '/$tenantSlug/content/documents'
    | '/$tenantSlug/content/instructors'
    | '/$tenantSlug/content/modules'
    | '/$tenantSlug/content/quizzes'
    | '/$tenantSlug/content/videos'
    | '/$tenantSlug/management/users'
    | '/$tenantSlug/site/configuration'
    | '/$tenantSlug/site/customization'
    | '/$tenantSlug/content/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/$tenantSlug'
    | '/__auth'
    | '/backoffice'
    | '/courses'
    | '/create-tenant'
    | '/profile'
    | '/__auth/forgot-password'
    | '/__auth/login'
    | '/__auth/reset-password'
    | '/__auth/signup'
    | '/backoffice/tenants'
    | '/backoffice/users'
    | '/courses/$courseSlug'
    | '/$tenantSlug/'
    | '/backoffice/'
    | '/courses/'
    | '/$tenantSlug/content/categories'
    | '/$tenantSlug/content/courses'
    | '/$tenantSlug/content/documents'
    | '/$tenantSlug/content/instructors'
    | '/$tenantSlug/content/modules'
    | '/$tenantSlug/content/quizzes'
    | '/$tenantSlug/content/videos'
    | '/$tenantSlug/management/users'
    | '/$tenantSlug/site/configuration'
    | '/$tenantSlug/site/customization'
    | '/$tenantSlug/content/quizzes/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantSlugRouteRoute: typeof TenantSlugRouteRouteWithChildren
  _authRouteRoute: typeof _authRouteRouteWithChildren
  BackofficeRouteRoute: typeof BackofficeRouteRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  CreateTenantRoute: typeof CreateTenantRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-tenant': {
      id: '/create-tenant'
      path: '/create-tenant'
      fullPath: '/create-tenant'
      preLoaderRoute: typeof CreateTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug': {
      id: '/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof TenantSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/backoffice/users': {
      id: '/backoffice/users'
      path: '/users'
      fullPath: '/backoffice/users'
      preLoaderRoute: typeof BackofficeUsersRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/tenants': {
      id: '/backoffice/tenants'
      path: '/tenants'
      fullPath: '/backoffice/tenants'
      preLoaderRoute: typeof BackofficeTenantsRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/__auth/signup': {
      id: '/__auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof _authSignupRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/$tenantSlug/site/customization': {
      id: '/$tenantSlug/site/customization'
      path: '/site/customization'
      fullPath: '/$tenantSlug/site/customization'
      preLoaderRoute: typeof TenantSlugSiteCustomizationRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/site/configuration': {
      id: '/$tenantSlug/site/configuration'
      path: '/site/configuration'
      fullPath: '/$tenantSlug/site/configuration'
      preLoaderRoute: typeof TenantSlugSiteConfigurationRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/management/users': {
      id: '/$tenantSlug/management/users'
      path: '/management/users'
      fullPath: '/$tenantSlug/management/users'
      preLoaderRoute: typeof TenantSlugManagementUsersRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/videos': {
      id: '/$tenantSlug/content/videos'
      path: '/content/videos'
      fullPath: '/$tenantSlug/content/videos'
      preLoaderRoute: typeof TenantSlugContentVideosRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/quizzes': {
      id: '/$tenantSlug/content/quizzes'
      path: '/content/quizzes'
      fullPath: '/$tenantSlug/content/quizzes'
      preLoaderRoute: typeof TenantSlugContentQuizzesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/modules': {
      id: '/$tenantSlug/content/modules'
      path: '/content/modules'
      fullPath: '/$tenantSlug/content/modules'
      preLoaderRoute: typeof TenantSlugContentModulesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/instructors': {
      id: '/$tenantSlug/content/instructors'
      path: '/content/instructors'
      fullPath: '/$tenantSlug/content/instructors'
      preLoaderRoute: typeof TenantSlugContentInstructorsRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/documents': {
      id: '/$tenantSlug/content/documents'
      path: '/content/documents'
      fullPath: '/$tenantSlug/content/documents'
      preLoaderRoute: typeof TenantSlugContentDocumentsRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/courses': {
      id: '/$tenantSlug/content/courses'
      path: '/content/courses'
      fullPath: '/$tenantSlug/content/courses'
      preLoaderRoute: typeof TenantSlugContentCoursesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/categories': {
      id: '/$tenantSlug/content/categories'
      path: '/content/categories'
      fullPath: '/$tenantSlug/content/categories'
      preLoaderRoute: typeof TenantSlugContentCategoriesRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/content/quizzes/$quizId': {
      id: '/$tenantSlug/content/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/$tenantSlug/content/quizzes/$quizId'
      preLoaderRoute: typeof TenantSlugContentQuizzesQuizIdRouteImport
      parentRoute: typeof TenantSlugContentQuizzesRoute
    }
  }
}

interface TenantSlugContentQuizzesRouteChildren {
  TenantSlugContentQuizzesQuizIdRoute: typeof TenantSlugContentQuizzesQuizIdRoute
}

const TenantSlugContentQuizzesRouteChildren: TenantSlugContentQuizzesRouteChildren =
  {
    TenantSlugContentQuizzesQuizIdRoute: TenantSlugContentQuizzesQuizIdRoute,
  }

const TenantSlugContentQuizzesRouteWithChildren =
  TenantSlugContentQuizzesRoute._addFileChildren(
    TenantSlugContentQuizzesRouteChildren,
  )

interface TenantSlugRouteRouteChildren {
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
  TenantSlugContentCategoriesRoute: typeof TenantSlugContentCategoriesRoute
  TenantSlugContentCoursesRoute: typeof TenantSlugContentCoursesRoute
  TenantSlugContentDocumentsRoute: typeof TenantSlugContentDocumentsRoute
  TenantSlugContentInstructorsRoute: typeof TenantSlugContentInstructorsRoute
  TenantSlugContentModulesRoute: typeof TenantSlugContentModulesRoute
  TenantSlugContentQuizzesRoute: typeof TenantSlugContentQuizzesRouteWithChildren
  TenantSlugContentVideosRoute: typeof TenantSlugContentVideosRoute
  TenantSlugManagementUsersRoute: typeof TenantSlugManagementUsersRoute
  TenantSlugSiteConfigurationRoute: typeof TenantSlugSiteConfigurationRoute
  TenantSlugSiteCustomizationRoute: typeof TenantSlugSiteCustomizationRoute
}

const TenantSlugRouteRouteChildren: TenantSlugRouteRouteChildren = {
  TenantSlugIndexRoute: TenantSlugIndexRoute,
  TenantSlugContentCategoriesRoute: TenantSlugContentCategoriesRoute,
  TenantSlugContentCoursesRoute: TenantSlugContentCoursesRoute,
  TenantSlugContentDocumentsRoute: TenantSlugContentDocumentsRoute,
  TenantSlugContentInstructorsRoute: TenantSlugContentInstructorsRoute,
  TenantSlugContentModulesRoute: TenantSlugContentModulesRoute,
  TenantSlugContentQuizzesRoute: TenantSlugContentQuizzesRouteWithChildren,
  TenantSlugContentVideosRoute: TenantSlugContentVideosRoute,
  TenantSlugManagementUsersRoute: TenantSlugManagementUsersRoute,
  TenantSlugSiteConfigurationRoute: TenantSlugSiteConfigurationRoute,
  TenantSlugSiteCustomizationRoute: TenantSlugSiteCustomizationRoute,
}

const TenantSlugRouteRouteWithChildren = TenantSlugRouteRoute._addFileChildren(
  TenantSlugRouteRouteChildren,
)

interface _authRouteRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authLoginRoute: typeof _authLoginRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
  _authSignupRoute: typeof _authSignupRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authLoginRoute: _authLoginRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
  _authSignupRoute: _authSignupRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface BackofficeRouteRouteChildren {
  BackofficeTenantsRoute: typeof BackofficeTenantsRoute
  BackofficeUsersRoute: typeof BackofficeUsersRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteRouteChildren: BackofficeRouteRouteChildren = {
  BackofficeTenantsRoute: BackofficeTenantsRoute,
  BackofficeUsersRoute: BackofficeUsersRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteRouteWithChildren = BackofficeRouteRoute._addFileChildren(
  BackofficeRouteRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantSlugRouteRoute: TenantSlugRouteRouteWithChildren,
  _authRouteRoute: _authRouteRouteWithChildren,
  BackofficeRouteRoute: BackofficeRouteRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  CreateTenantRoute: CreateTenantRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
